[libdefaults]
    default_realm = OPTIMEDIT.EU
    dns_lookup_realm = false
    dns_lookup_kdc = true
    rdns = false
    ticket_lifetime = 24h
    forwardable = true
    default_tgs_enctypes = aes256-cts-hmac-sha1-96 aes128-cts-hmac-sha1-96
    default_tkt_enctypes = aes256-cts-hmac-sha1-96 aes128-cts-hmac-sha1-96

[realms]
    OPTIMEDIT.EU = {
        kdc = OPT-DC02.optimedit.eu
        admin_server = OPT-DC02.optimedit.eu
    }

[domain_realm]
    .optimedit.eu = OPTIMEDIT.EU
    optimedit.eu = OPTIMEDIT.EU
