---
# Emplacement /projet_optimedit/Git/03.01.play_iis_install_http.yml -- STABLE --
- name: "Préparation et Déploiement des 13 sites HTTP"
  hosts: srv_iis
  gather_facts: false
  vars:
    enable_ssl: false
    
  roles:
    - iis_setup
